---
version: '3.8'

services:
  app:
    image: personal-website
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # expose:
    #   - '3000'
    # networks:
    #   - proxy

# networks:
#   proxy:
#     external: true