---
name: personal-website

services:
  app:
    #image: personal-website
    image: images.bautistahome.com/itsageba/personal-website:0.5.2 # please update every new version
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # expose:
    #   - '3000'
    # networks:
    #   - proxy

# networks:
#   proxy:
#     external: true