#
# .gitea/gitea-build-image.yaml
#

name: Test, Build, and Deploy
run-name: ${{ gitea.actor }} is running CI/CD Pipeline
on: 
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: geba
      DOCKER_ORG2: itsageba
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NEXT_PUBLIC_STRAPI_API_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          envkey_NEXT_PUBLIC_PAGE_LIMIT: ${{ secrets.STRAPI_PAGE_LIMIT }}
          envkey_NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
          file_name: .env
          fail_on_empty: true

      - name: Get Docker Metadata
        id: dmeta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            gitea.bautistahome.com/miguelangelobautista/personal-website 
            images.bautistahome.com/itsageba/personal-website            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          config-inline: |
            [registry."gitea.bautistahome.com"]
            [registry."images.bautistahome.com"]        

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: gitea.bautistahome.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to gitea
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64                     
          push: true
          labels: ${{ steps.dmeta.outputs.labels }}
          tags: ${{ steps.dmeta.outputs.tags}}