#
# .gitea/gitea-ci.yaml
#

name: Build And Test
run-name: ${{ gitea.actor }} is running CI/CD Pipeline
on: 
  push #:
    # branches:
    #   - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4
      - name: Use Node.js
        uses: https://github.com/actions/setup-node@v3
        with:
          node-version: '20.13'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

  publish:
    runs-on: ubuntu-latest
    needs: build
    #if: gitea.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."gitea.bautistahome.com"]
              http = false
              insecure = false            
      # - name: Build and push Docker image to gitea Registry
      #   uses: https://github.com/docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: "images.bautistahome.com/itsageba/personal-website:${{gitea.sha}},images.bautistahome.com/itsageba/personal-website:latest"
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: https://gitea.bautistahome.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get Meta
        id: Meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT
      
      - name: Build and push to gitea
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64                        
          push: true
          tags: | # replace it with your local IP and tags
            gitea.bautistahome.com/itsageba/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
            gitea.bautistahome.com/itsageba/${{ steps.meta.outputs.REPO_NAME }}:latest}