#
# .gitea/run-lint.yaml
#
name: Lint
run-name: ${{ gitea.actor }} is Linting
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js 20.13.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.13.0
    - run: npm ci
    - run: npm run lint
